### ISSUE TITLE
Unable To Find the Image from the Build Step When Running in Self-Hosted Runner

### ISSUE THREAD

**Issue by Stoyan12314** [phwt/sonarqube-quality-gate-action#23]
```
Run phwt/sonarqube-quality-gate-action@v1
  with:
    sonar-project-key: Flowcontrol_Article_Module
    sonar-host-url: ***
    sonar-token: ***
    github-token: ***
    disable-pr-comment: false
    fail-on-quality-gate-error: false
  env:
    JAVA_HOME: /home/flowcontrol/Desktop/runners/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/18.0.[2](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:2)-101/x64
    JAVA_HOME_18_X64: /home/flowcontrol/Desktop/runners/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/18.0.2-101/x64
/usr/local/bin/docker run --name ac126852e5e4ae0cf54a70b8afdce58[3](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:3)3[4](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:4)[5](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:5)959_de[6](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:6)3e5 --label ac1268 --workdir /github/workspace --rm -e "JAVA_HOME" -e "JAVA_HOME_18_X64" -e "INPUT_SONAR-PROJECT-KEY" -e "INPUT_SONAR-HOST-URL" -e "INPUT_SONAR-TOKEN" -e "INPUT_GITHUB-TOKEN" -e "INPUT_DISABLE-PR-COMMENT" -e "INPUT_FAIL-ON-QUALITY-GATE-ERROR" -e "INPUT_BRANCH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/flowcontrol/Desktop/runners/actions-runner/_work/_temp/_github_home":"/github/home" -v "/home/flowcontrol/Desktop/runners/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/flowcontrol/Desktop/runners/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/flowcontrol/Desktop/runners/actions-runner/_work/RP-Flowcontrol/RP-Flowcontrol":"/github/workspace" ac1268:52e5e4ae0cf54a[7](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:7)0b[8](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:8)afdce583345[9](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:9)59
Unable to find image 'ac[12](https://github.com/rikp777/RP-Flowcontrol/actions/runs/8326066021/job/22781091312#step:13:13)68:52e5e4ae0cf54a70b8afdce583345959' locally
docker: Error response from daemon: pull access denied for ac1268, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
